"use client";
import { useState } from "react";
import { Check, ChevronRight, ImagePlus, Package, PawPrint, Sparkles } from "lucide-react";

const titles=["宠物医院采购留置针，需要关注什么？","22G、24G、26G 留置针规格怎么看？","一盒 100 支｜百仕韦动物留置针资料展示"];
export function PetContentWorkspace(){
  const [step,setStep]=useState<"ready"|"generating"|"review"|"queued">("ready"); const [title,setTitle]=useState(0);
  const [copy,setCopy]=useState("宠物医院和诊所在采购静脉留置针时，首先需要核对产品资料与实际使用需求。\n\n目前资料库已确认：百仕韦动物专用一次性使用静脉留置针，规格为 22G / 24G / 26G，包装为 100 支/盒。其他用途、适用范围及注意事项请以管理员录入的真实资料为准。\n\n如需了解批发与渠道合作信息，欢迎进一步沟通。");
  function generate(){setStep("generating");setTimeout(()=>setStep("review"),900)}
  if(step==="generating") return <div className="grid min-h-[calc(100vh-4rem)] place-items-center p-8"><div className="text-center"><Sparkles className="mx-auto h-12 w-12 animate-pulse text-[#17604b]"/><h2 className="mt-5 text-2xl font-semibold">正在基于真实产品资料生成</h2><p className="mt-2 text-sm text-muted-foreground">选题、标题、正文、标签与 5 张图片方案</p><div className="mx-auto mt-7 h-2 w-80 overflow-hidden rounded-full bg-slate-200"><i className="block h-full w-3/4 animate-pulse rounded-full bg-[#17604b]"/></div></div></div>;
  if(step==="queued") return <div className="grid min-h-[calc(100vh-4rem)] place-items-center p-8"><div className="text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-100 text-[#17604b]"><Check/></span><h2 className="mt-5 text-2xl font-semibold">已进入待发布队列</h2><p className="mt-2 text-sm text-muted-foreground">计划发布：明天 10:30 · 小红书 · 发布前仍可修改</p><button onClick={()=>setStep("ready")} className="mt-6 rounded-lg bg-[#174d3b] px-5 py-2.5 text-sm font-medium text-white">返回智能体首页</button></div></div>;
  return <div className="mx-auto max-w-7xl space-y-6 p-8">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-[#17604b]">第一阶段核心流水线</p><h2 className="mt-1 text-2xl font-semibold">真实资料驱动的小红书内容生产</h2></div><button onClick={generate} className="flex items-center gap-2 rounded-lg bg-[#174d3b] px-5 py-3 text-sm font-semibold text-white shadow-sm"><Sparkles className="h-4 w-4"/>生成今日小红书</button></div>
    <div className="flex flex-wrap items-center gap-2 rounded-xl border bg-white p-4 text-xs">{["产品资料","AI 选题","AI 图片","AI 配文","人工审核","发布队列"].map((x,i)=><div key={x} className="flex items-center gap-2"><span className={`rounded-full px-3 py-1.5 ${step==="review"&&i<5?"bg-emerald-50 text-[#17604b]":"bg-slate-100 text-slate-500"}`}>{x}</span>{i<5&&<ChevronRight className="h-3 w-3 text-slate-300"/>}</div>)}</div>
    {step==="ready"?<div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <section className="rounded-2xl border bg-white p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-[#17604b]"><Package/></span><div><h3 className="font-semibold">当前产品资料</h3><p className="text-xs text-muted-foreground">AI 唯一事实来源</p></div><span className="ml-auto rounded-full bg-emerald-50 px-3 py-1 text-xs text-[#17604b]">真实性保护开启</span></div><div className="mt-6 grid gap-4 rounded-xl bg-slate-50 p-5 sm:grid-cols-2"><div><small className="text-muted-foreground">品牌</small><p className="mt-1 font-medium">百仕韦</p></div><div><small className="text-muted-foreground">产品</small><p className="mt-1 font-medium">动物专用一次性使用静脉留置针</p></div><div><small className="text-muted-foreground">规格</small><p className="mt-1 font-medium">22G / 24G / 26G</p></div><div><small className="text-muted-foreground">包装</small><p className="mt-1 font-medium">100 支/盒</p></div></div><p className="mt-4 text-xs leading-6 text-muted-foreground">未录入的用途、适用范围、厂家、有效期等信息，AI 不会自行补充。</p></section>
      <section className="rounded-2xl border bg-[#153f34] p-6 text-white"><PawPrint className="h-8 w-8 text-amber-200"/><h3 className="mt-5 text-xl font-semibold">今天只需 1～3 分钟</h3><p className="mt-3 text-sm leading-7 text-emerald-50/70">系统完成选题、文案与图片方案，你只负责核对真实信息并审核。</p><div className="mt-6 flex items-center gap-3 rounded-xl bg-white/10 p-4"><ImagePlus/><div><b className="text-sm">真实产品图优先</b><p className="text-xs text-emerald-50/60">AI 只生成背景与排版</p></div></div></section>
    </div>:<div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <section className="rounded-2xl border bg-white p-6"><div className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-[#17604b]"><Check className="mr-2 inline h-4 w-4"/>真实性检查通过：仅引用品牌、产品、规格、包装数量</div><h3 className="font-semibold">选择标题</h3>{titles.map((x,i)=><button key={x} onClick={()=>setTitle(i)} className={`mt-3 block w-full rounded-lg border p-3 text-left text-sm ${title===i?"border-[#17604b] bg-emerald-50":"border-slate-200"}`}>{title===i?"●":"○"}　{x}</button>)}<h3 className="mb-2 mt-6 font-semibold">正文</h3><textarea value={copy} onChange={e=>setCopy(e.target.value)} className="h-56 w-full rounded-lg border border-slate-200 p-4 text-sm leading-7 outline-none focus:border-[#17604b]"/><div className="mt-4 flex flex-wrap gap-2">{["#宠物医院","#宠物医疗耗材","#静脉留置针","#兽医采购","#宠物诊所"].map(x=><span key={x} className="rounded-md bg-emerald-50 px-2.5 py-1 text-xs text-[#17604b]">{x}</span>)}</div></section>
      <section><div className="rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">5 张图片方案</h3><p className="mt-1 text-xs text-muted-foreground">3:4 · 真实素材 + AI 背景 + 程序排版</p></div><button className="text-xs text-[#17604b]">上传真实素材</button></div><div className="mt-5 grid grid-cols-3 gap-3">{["采购留置针\n先看这 3 点","真实产品展示","规格信息","宠物医院场景","批发合作咨询"].map((x,i)=><div key={x} className={`flex aspect-[3/4] flex-col justify-between rounded-lg p-3 text-xs ${i===1?"bg-emerald-100 text-[#174d3b]":"bg-[#174d3b] text-white"}`}><span>{i+1}/5</span><b className="whitespace-pre-line">{x}</b><small className="opacity-60">{i===1?"真实素材占位":"AI 背景"}</small></div>)}</div></div><button onClick={()=>setStep("queued")} className="mt-4 w-full rounded-lg bg-[#174d3b] px-5 py-3 text-sm font-semibold text-white"><Check className="mr-2 inline h-4 w-4"/>审核通过并加入发布队列</button></section>
    </div>}
  </div>;
}
